Import Libraries

In [1]:
import pandas as pd
import sqlite3
import json
from bs4 import BeautifulSoup

**TASK 1**

Select and naming files

In [2]:
DB_FILE = "library.db"
JSON_FILE = "book_catalog.json"
HTML_FILE = "reading_kickoff.html"

Connect with database

In [3]:
conn = sqlite3.connect(DB_FILE)

Know existed tables

In [4]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';",conn)
tables

        name
0    members
1      books
2  checkouts

Show Members Data

Import Libraries

In [5]:
import pandas as pd
import sqlite3
import json
from bs4 import BeautifulSoup

**TASK 1**

Select and naming files

In [6]:
DB_FILE = "library.db"
JSON_FILE = "book_catalog.json"
HTML_FILE = "reading_kickoff.html"

Connect with database

In [7]:
conn = sqlite3.connect(DB_FILE)

Know existed tables

In [8]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';",conn)
tables

        name
0    members
1      books
2  checkouts

Show Members Data

In [9]:
members = pd.read_sql_query("SELECT * FROM members;",conn)
members.head()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,NaN
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05

Checkouts

In [10]:
checkouts = pd.read_sql_query("SELECT * FROM checkouts;",conn)
checkouts.head()

   checkout_id  member_id  book_id checkout_date return_date
0         9263       1047      517    2024-10-21  2024-11-07
1         9340       1072      513    2025-08-24  2025-09-01
2         9231       1053      523    2024-02-04  2024-02-16
3         9129       1032      513    2025-06-21  2025-06-29
4         9370       1079      511    2025-11-11  2025-12-03

Books

In [11]:
books = pd.read_sql_query("SELECT * FROM books;",conn)

books.head()

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez



---

*Question 1*

In [12]:
query1 = """
SELECT m.member_id,m.first_name,m.last_name,COUNT(c.checkout_id) AS checkout_count
FROM members AS m
LEFT JOIN checkouts AS c
ON m.member_id = c.member_id
GROUP BY
    m.member_id,
    m.first_name,
    m.last_name
ORDER BY m.member_id;
"""

answer1 = pd.read_sql_query(query1, conn)

answer1

    member_id first_name last_name  checkout_count
0        1001      Salma   Ibrahim               1
1        1002      Fares     Saleh               2
2        1003     Bassel    Hegazy               9
3        1004      Fares     Wahba               0
4        1005    Youssef     Halim               3
..        ...        ...       ...             ...
75       1076       Dina     Wahba               7
76       1077       Lina    Rashad               6
77       1078     Habiba     Osman               0
78       1079       Rana     Osman              10
79       1080     Bassel     Wahba               2

[80 rows x 4 columns]

*Question 2*

In [13]:
pattern = "%a%"

query2 = f"""
SELECT
book_id,
title,
author
FROM books
WHERE author LIKE '{pattern}';
"""

answer2 = pd.read_sql_query(query2, conn)

answer2

    book_id                    title          author
0       501          The Silver Kite   Amina Darwish
1       502           Desert Compass   Amina Darwish
2       503        The Lantern Maker    Adel Roushdy
3       504      Rooftop Astronomers    Adel Roushdy
4       505      Letters to the Nile       Aya Hafez
5       506      The Paper Boat Club       Aya Hafez
6       507    Fossils and Fireflies     Dalia Serry
7       508    The Quiet Observatory     Dalia Serry
8       509      Marbles and Mirrors     Diaa Sultan
9       510    The Missing Metronome     Diaa Sultan
10      511     Winter in Alexandria    Farida Anwar
11      512   The Cartographer's Cat    Farida Anwar
12      513   Circuits for Beginners    Galal Mounir
13      514    The Robot in Row Nine    Galal Mounir
14      515       Songs of the Oasis      Hoda Bakry
15      516  The Beekeeper's Almanac      Hoda Bakry
16      517  Shadows on the Corniche     Hani Nagati
17      518     The Ninth Lighthouse     Hani Nagati
18      519         Kites Over Cairo  Jasmine Wahdan
19      520     The Copper Telescope  Jasmine Wahdan
20      521    A Garden of Equations      Karim Elwy
21      522      The Puzzle Merchant      Karim Elwy
22      523    Footsteps in the Dust    Laila Shokry
23      524    The Weaver's Daughter    Laila Shokry
24      525     Storms and Sailboats   Mahmoud Rafei
25      526    The Clockwork Orchard   Mahmoud Rafei
26      527     Notes from the Delta  Mona Kholoussy
27      528        The Glass Beehive  Mona Kholoussy
28      529   Riddles of the Red Sea    Sara Tantawy
29      530        The Sandstone Key    Sara Tantawy
30      531    Voices in the Library     Samir Zohdy
31      532        The Last Bookmark     Samir Zohdy

*Question 3*

In [14]:
query3 = """
SELECT
b.book_id,
b.title,
COUNT(c.checkout_id) AS checkout_count
FROM books AS b
JOIN checkouts AS c
ON b.book_id = c.book_id
GROUP BY
b.book_id,
b.title
ORDER BY checkout_count DESC
LIMIT 5;
"""

answer3 = pd.read_sql_query(query3, conn)

answer3

   book_id                   title  checkout_count
0      501         The Silver Kite              57
1      507   Fossils and Fireflies              55
2      513  Circuits for Beginners              46
3      519        Kites Over Cairo              38
4      525    Storms and Sailboats              25

*Question 4*

In [15]:
query4 = """
SELECT
m.member_id,
m.first_name,
m.last_name,
COUNT(c.checkout_id) AS book_count
FROM members AS m
JOIN checkouts AS c
ON m.member_id = c.member_id
GROUP BY
m.member_id,
m.first_name,
m.last_name
ORDER BY book_count DESC
LIMIT 10;
"""

answer4 = pd.read_sql_query(query4, conn)

answer4

   member_id first_name last_name  book_count
0       1034        Aya     Wahba          25
1       1044     Sherif     Saleh          21
2       1008       Ziad     Saleh          19
3       1010       Nour     Nabil          18
4       1027    Mostafa     Fouad          18
5       1018      Ahmed    Shafik          17
6       1024    Youssef    Hegazy          17
7       1065       Adam     Fahmy          17
8       1030       Reem     Osman          16
9       1047       Sara    Rashad          16

*Question 5*

In [16]:
chosen_neighborhood = "Maadi"

query5 = f"""
SELECT
c.checkout_id,
c.member_id,
c.book_id,
c.checkout_date,
c.return_date
FROM checkouts AS c
JOIN members AS m
ON c.member_id = m.member_id
WHERE m.neighborhood = '{chosen_neighborhood}'
ORDER BY c.checkout_date DESC
LIMIT 10 OFFSET 10;
"""

answer5 = pd.read_sql_query(query5, conn)

answer5

   checkout_id  member_id  book_id checkout_date return_date
0         9103       1003      513    2025-09-04  2025-09-25
1         9081       1017      502    2025-08-25  2025-09-17
2         9001       1008      501    2025-08-23  2025-08-28
3         9050       1003      521    2025-08-21         NaN
4         9085       1018      525    2025-08-19  2025-09-18
5         9055       1015      525    2025-08-08  2025-08-27
6         9023       1018      503    2025-08-04  2025-08-27
7         9004       1013      519    2025-07-27  2025-08-16
8         9051       1003      513    2025-07-22  2025-08-18
9         9010       1009      513    2025-07-22  2025-08-16



---

Count total books for each member

In [17]:
member_book_counts = (checkouts.groupby("member_id").size().reset_index(name="total_books_borrowed"))

member_book_counts.head()

   member_id  total_books_borrowed
0       1001                     1
1       1002                     2
2       1003                     9
3       1005                     3
4       1006                     1

Add book counts to members

In [18]:
members_with_counts = members.merge(member_book_counts,on="member_id",how="left")

members_with_counts["total_books_borrowed"] = (members_with_counts["total_books_borrowed"].fillna(0).astype(int))

members_with_counts.head()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05,1
1,1002,Fares,Saleh,9.0,Maadi,Active,NaN,2
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,9
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09,0
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05,3

Merge Members with Chckouts

In [19]:
combined_stage1 = checkouts.merge(
    members_with_counts,
    on="member_id",
    how="left"
)

combined_stage1.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,16
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,14
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,5
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,6
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,10

Make sure not to miss checkouts

In [20]:
print("Original checkouts:", len(checkouts))
print("After Stage 1:", len(combined_stage1))

Original checkouts: 391
After Stage 1: 391

Succeed



---

Read book Catalog

In [21]:
with open(JSON_FILE, "r", encoding="utf-8") as f:
    catalog = json.load(f)

catalog_df = pd.DataFrame(catalog)

catalog_df.head()

   book_id       genre  pages  publication_year            publisher
0      501   Adventure    128            2017.0           Nile Press
1      502   Adventure    109            2018.0          Delta House
2      503  Historical    259               NaN           Nile Press
3      504     Science    319            2009.0  Cairo Young Readers
4      505  Historical    216            2024.0          Oasis Books

Show book columns

In [22]:
catalog_df.columns

Index(['book_id', 'genre', 'pages', 'publication_year', 'publisher'], dtype='str')

Merge book details

In [23]:
combined_stage2 = combined_stage1.merge(books,on="book_id",how="left")

combined_stage2.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed,title,author
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,16,Shadows on the Corniche,Hani Nagati
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,14,Circuits for Beginners,Galal Mounir
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,5,Footsteps in the Dust,Laila Shokry
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,6,Circuits for Beginners,Galal Mounir
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,10,Winter in Alexandria,Farida Anwar

Add json data

In [24]:
combined_stage2 = combined_stage2.merge(catalog_df,on="book_id",how="left")

combined_stage2.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed,title,author,genre,pages,publication_year,publisher
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,16,Shadows on the Corniche,Hani Nagati,Mystery,338,2015.0,Delta House
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,14,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,5,Footsteps in the Dust,Laila Shokry,Historical,276,2018.0,Oasis Books
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,6,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,10,Winter in Alexandria,Farida Anwar,Historical,117,2016.0,Nile Press

Verifying the number of rows

In [25]:
print("Before adding book details:", len(combined_stage1))
print("After adding book details:", len(combined_stage2))

Before adding book details: 391
After adding book details: 391



---

*Reading Kickoff HTML*

Open html

In [26]:
with open(HTML_FILE, "r", encoding="utf-8") as f:
    soup = BeautifulSoup(f, "html.parser")

Extracting tables

In [27]:
tables_html = pd.read_html(HTML_FILE)

len(tables_html)

1

show reading kickoff table

In [28]:
kickoff = tables_html[0]

kickoff.head()

   Member ID  Book ID Checkout Date
0       1026      522    2025-07-11
1       1049      520    2025-07-11
2       1062      525    2025-07-05
3       1065      520    2025-07-07
4       1104      515    2025-07-07

Knowing columns

In [29]:
kickoff.columns

Index(['Member ID', 'Book ID', 'Checkout Date'], dtype='str')

adding reading kickoff

In [30]:
print(kickoff.columns)

Index(['Member ID', 'Book ID', 'Checkout Date'], dtype='str')

In [31]:
kickoff = kickoff.rename(columns={"Member ID": "member_id","Book ID": "book_id","Checkout Date": "checkout_date"})

kickoff_combined = kickoff.merge(members_with_counts,on="member_id",how="left")

kickoff_combined.head()

,member_id,book_id,checkout_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed
0,1026,522,2025-07-11,Nada,Saleh,7.0,Nasr City,inactive,2023-11-16,3.0
1,1049,520,2025-07-11,Ahmed,Gamal,6.0,Heliopolis,Active,2023-06-10,1.0
2,1062,525,2025-07-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,7.0
3,1065,520,2025-07-07,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,17.0
4,1104,515,2025-07-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
print(kickoff_combined.columns.tolist())

['member_id', 'book_id', 'checkout_date', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'total_books_borrowed']

Add books

In [33]:
kickoff_combined = kickoff_combined.merge(books,on="book_id",how="left")

Add catalog

In [34]:
kickoff_combined = kickoff_combined.merge(catalog_df,on="book_id",how="left")

Combine columns

In [35]:
print(combined_stage2.columns.tolist())
print(kickoff_combined.columns.tolist())

['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'total_books_borrowed', 'title', 'author', 'genre', 'pages', 'publication_year', 'publisher']
['member_id', 'book_id', 'checkout_date', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'total_books_borrowed', 'title', 'author', 'genre', 'pages', 'publication_year', 'publisher']

In [36]:
# Rename the book title and author columns if needed
kickoff_combined = kickoff_combined.rename(
    columns={
        "title_x": "title",
        "author_x": "author"
    }
)

# Remove duplicate columns only if they exist
kickoff_combined = kickoff_combined.drop(
    columns=["title_y", "author_y"],
    errors="ignore"
)

kickoff_combined.head()

,member_id,book_id,checkout_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed,title,author,genre,pages,publication_year,publisher
0,1026,522,2025-07-11,Nada,Saleh,7.0,Nasr City,inactive,2023-11-16,3.0,The Puzzle Merchant,Karim Elwy,Mystery,104,2016.0,Cairo Young Readers
1,1049,520,2025-07-11,Ahmed,Gamal,6.0,Heliopolis,Active,2023-06-10,1.0,The Copper Telescope,Jasmine Wahdan,Science Fiction,136,2009.0,Oasis Books
2,1062,525,2025-07-05,Tarek,Adel,7.0,Zamalek,Active,2023-01-22,7.0,Storms and Sailboats,Mahmoud Rafei,Adventure,297,2015.0,Oasis Books
3,1065,520,2025-07-07,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,17.0,The Copper Telescope,Jasmine Wahdan,Science Fiction,136,2009.0,Oasis Books
4,1104,515,2025-07-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Songs of the Oasis,Hoda Bakry,Poetry,316,2022.0,Cairo Young Readers

Add missing checkout coloumns and arrange coloumns

In [37]:
# Add missing checkout columns
kickoff_combined["checkout_id"] = pd.NA
kickoff_combined["return_date"] = pd.NA

# Arrange columns in the exact same order
kickoff_combined = kickoff_combined[
    combined_stage2.columns
]

print(kickoff_combined.columns.tolist())

['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'total_books_borrowed', 'title', 'author', 'genre', 'pages', 'publication_year', 'publisher']

In [38]:
print("Database:", list(combined_stage2.columns))
print("Kickoff:", list(kickoff_combined.columns))
print(list(combined_stage2.columns) == list(kickoff_combined.columns))

Database: ['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'total_books_borrowed', 'title', 'author', 'genre', 'pages', 'publication_year', 'publisher']
Kickoff: ['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'total_books_borrowed', 'title', 'author', 'genre', 'pages', 'publication_year', 'publisher']
True

In [39]:
task1_combined_data = pd.concat([combined_stage2, kickoff_combined],ignore_index=True)

task1_combined_data.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,total_books_borrowed,title,author,genre,pages,publication_year,publisher
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,16.0,Shadows on the Corniche,Hani Nagati,Mystery,338,2015.0,Delta House
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,14.0,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,5.0,Footsteps in the Dust,Laila Shokry,Historical,276,2018.0,Oasis Books
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,6.0,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,10.0,Winter in Alexandria,Farida Anwar,Historical,117,2016.0,Nile Press

In [40]:
print("Database checkouts:", len(combined_stage2))
print("Reading Kickoff checkouts:", len(kickoff_combined))
print("Total combined records:", len(task1_combined_data))

Database checkouts: 391
Reading Kickoff checkouts: 26
Total combined records: 417

In [41]:
print(len(combined_stage2) + len(kickoff_combined)== len(task1_combined_data))

True

Save file

In [42]:
task1_combined_data.to_csv("31010280200518-Library-task1_combined_data.csv",index=False)

In [43]:
import os

file_name ="31010280200518-Library-task1_combined_data.csv"

print(os.path.exists(file_name))
print(os.path.getsize(file_name), "bytes")

True
61414 bytes

---

Save SQL answers file

In [44]:
sql_report = f"""
SQL QUESTION 1
How much is each member borrowing?

SQL QUERY:
{query1}

RESULT:
{answer1.to_string(index=False)}

------------------

SQL QUESTION 2
Which books match a chosen author pattern?

Chosen pattern: {pattern}

SQL QUERY:
{query2}

RESULT:
{answer2.to_string(index=False)}

--------------------------

SQL QUESTION 3
What are the five most popular books?

SQL QUERY:
{query3}

RESULT:
{answer3.to_string(index=False)}

---------------------

SQL QUESTION 4
Who are the ten most active readers?

SQL QUERY:
{query4}

RESULT:
{answer4.to_string(index=False)}

-----------------

SQL QUESTION 5
Neighborhood activity further back in time

Chosen neighborhood: {chosen_neighborhood}

SQL QUERY:
{query5}

RESULT:
{answer5.to_string(index=False)}

---------------------

WEB PAGE VS API REFLECTION

The Reading Kickoff data came from an HTML web page, which is designed mainly for people to read in a browser. An API, on the other hand, provides data directly to programs in a structured and predictable format.

For this project, the difference mattered because the Reading Kickoff data had to be extracted from an HTML table before it could be combined with the database data. If the same information had been provided through an API, it would likely have been easier to access and process automatically.
"""

with open("31010280200518-Library-task1_sql_answers.txt","w",encoding="utf-8") as f:
    f.write(sql_report)